### ISSUE TITLE
pyb.Flash seems to point to QSPI

### ISSUE THREAD

**Issue by stepansnigirev** [diybitcoinhardware/f469-disco#20]
When I create pyb.Flash() and check the size of the flash it gives me ~16 MB that is the size of QSPI, not the size of the internal flash memory.
We need a way to control writing to flash and to qspi from micropython.

One way would be to make two separate block devices that we could control from micropython, i.e. pyb.Flash() and pyb.QSPI().
Alternatively we just need to make sure that qspi is mounted to qspi, and pyb.Flash is pointing to real flash.

@miketlk

**Comment by miketlk** [comment]
Thanks. I will check it and get back here. Because the support of two separate flash devices is not an official feature it is actually quite fragile and was broken at least once with MicroPython update.

@stepansnigirev

**Comment by miketlk** [comment]
It looks like I fixed it with PR #21.

Now if internal Flash storage is erased it is formatted on start-up and mounted correctly.
Please note that there is a new limitation: when dual flash storage is enabled, both Flash storage devices support only FAT file systems. Previously LittleFS was allowed as well but only for internal Flash memory.

**Comment by stepansnigirev** [comment]
Update:
`pyb.Flash()` gives access to both internal flash and QSPI.

## Blocks table:

| start | section |
| -----|---------|
| 0 | MBR |
| 1-255 | reserved |
| 256 - 447 | internal flash |
| 448 - 33215 | QSPI |
